// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6DDGSUGgpZaoSi8OdyriV75YELjyL4vc',
    appId: '1:877082113612:web:966352cdc179f3e626e6e9',
    messagingSenderId: '877082113612',
    projectId: 'fir-1-2b753',
    authDomain: 'fir-1-2b753.firebaseapp.com',
    databaseURL: 'https://fir-1-2b753-default-rtdb.firebaseio.com',
    storageBucket: 'fir-1-2b753.appspot.com',
    measurementId: 'G-SQBLM1QP22',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9BDiK7yQ9abYabRQqNGWoCOJ4Nr_zHBk',
    appId: '1:877082113612:android:adf47a2f865fe6af26e6e9',
    messagingSenderId: '877082113612',
    projectId: 'fir-1-2b753',
    databaseURL: 'https://fir-1-2b753-default-rtdb.firebaseio.com',
    storageBucket: 'fir-1-2b753.appspot.com',
  );
}
